### PR TITLE
Adds Navbar

### PR DESCRIPTION
**Pull request by Im-Madhur-Gupta**
Features added:
Navbar

Dependenices:
react-router-dom
sass

### CODE REVIEW

**Review by prathmeshkhandelwal1 — COMMENTED** [review]
While clicking on cards directly, routes are changing but cards are not!

**Review by prathmeshkhandelwal1 — CHANGES_REQUESTED** [review]
While clicking on cards directly, routes are changing but cards are not!

**Comment by Im-Madhur-Gupta** [comment]
From now onwards I will try to reduce the number of commits I make @prathmeshkhandelwal1 sir.

**Comment by prathmeshkhandelwal1** [comment]
@Im-Madhur-Gupta Make cursor pointer in cards

**Pull request merged**
